# Generated by Django 3.0.5 on 2020-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=20)),
                ('type', models.CharField(choices=[('C', 'Credit'), ('D', 'Debit')], max_length=1)),
                ('category', models.CharField(choices=[('S', 'Salary'), ('P', 'Personal'), ('R', 'Rent'), ('F', 'Food'), ('B', 'Bills'), ('O', 'Others')], max_length=1)),
                ('description', models.CharField(max_length=30)),
                ('is_recurring', models.BooleanField()),
            ],
        ),
    ]
